
spring:
  application:
    name: match-api
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    h2:
      console:
        enabled: true
        path: /h2-console
server:
    port: 8090


accounts:
    host: http://localhost:8080/accounts/v1/suppliers